import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import CarouselComponent from "../components/carousel/carousel";
import { useGetSlides } from "../services/slide/slide.service";
import { useGetUserInfo } from "../services/user/user.service";
import styles from "../styles/Home.module.css";

const About: NextPage = () => {
  const slides = useGetSlides()

  const user = useGetUserInfo()

  if (slides.isLoading || slides.isLoading) return <div>loading...</div>
  if (slides.error) return <div>error...</div>

  if (user.isLoading || user.isLoading) return <div>loading...</div>
  if (user.error) return <div>error...</div>

  console.log('********user**********');
  console.log(user);
  console.log('******************');

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        About
        </h1>
        <CarouselComponent title="hello" slides={slides.data as any}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default About;
